### ISSUE TITLE
Error with getDirectorySize

### ISSUE THREAD

**Issue by subwolf** [Storj/farmer#11]
Testing on my Synology NAS, got a TB spare so I'm using it to test the farmer.

````
/usr/lib/node_modules/storj-farmer/bin/farmer.js:207
    getDirectorySize(config.storage.path, function(err, size) {
                           ^

TypeError: Cannot read property 'storage' of undefined
    at send (/usr/lib/node_modules/storj-farmer/bin/farmer.js:207:28)
    at report [as _onTimeout] (/usr/lib/node_modules/storj-farmer/bin/farmer.js:284:5)
    at Timer.listOnTimeout (timers.js:92:15)
````

**Comment by subwolf** [comment]
Default path here is /root/.storj-farmer-cli/

**Comment by gordonwritescode** [comment]
I think this is a duplicate solved with https://github.com/Storj/farmer/pull/10
