### ISSUE TITLE
occasional error in logfile: "not opened"

### ISSUE THREAD

**Issue by lucvanbraekel** [Storj/farmer#17]
```
Error: not opened
    at WebSocket.send (/usr/local/lib/node_modules/storj-farmer/node_modules/ws/lib/WebSocket.js:219:16)
    at WebSocket.<anonymous> (/usr/local/lib/node_modules/storj-farmer/node_modules/storj/lib/datachannel/server.js:108:21)
    at emitTwo (events.js:105:20)
    at WebSocket.emit (events.js:185:7)
    at Receiver.onbinary (/usr/local/lib/node_modules/storj-farmer/node_modules/ws/lib/WebSocket.js:848:10)
    at /usr/local/lib/node_modules/storj-farmer/node_modules/ws/lib/Receiver.js:628:18
    at /usr/local/lib/node_modules/storj-farmer/node_modules/ws/lib/Receiver.js:368:7
    at /usr/local/lib/node_modules/storj-farmer/node_modules/ws/lib/PerMessageDeflate.js:249:5
    at afterWrite (_stream_writable.js:355:3)
    at onwrite (_stream_writable.js:346:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at afterTransform (_stream_transform.js:79:3)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Zlib.callback (zlib.js:613:5)
```

**Comment by CurreE** [comment]
I got this error too.  I've had storjfarm running continuously since Friday evening.  Woke up this morning and found it had crashed overnight with this error.  Here's my log snippet:

```
{"type":"info","message":"sending PING message to {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460821295111}","timestamp":"2016-04-16T15:41:35.111Z"}
{"type":"info","message":"sending PING message to {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460821295111}","timestamp":"2016-04-16T15:41:35.111Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460821296554}","timestamp":"2016-04-16T15:41:36.554Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460821296554}","timestamp":"2016-04-16T15:41:36.554Z"}
/usr/local/lib/node_modules/storj-farmer/node_modules/myspeed/node_modules/ws/lib/WebSocket.js:219
    else throw new Error('not opened');
         ^

Error: not opened
    at WebSocket.send (/usr/local/lib/node_modules/storj-farmer/node_modules/myspeed/node_modules/ws/lib/WebSocket.js:219:16)
    at RandomStream.<anonymous> (/usr/local/lib/node_modules/storj-farmer/node_modules/myspeed/lib/client.js:45:10)
    at emitOne (events.js:77:13)
    at RandomStream.emit (events.js:169:7)
    at readableAddChunk (/usr/local/lib/node_modules/storj-farmer/node_modules/myspeed/node_modules/noisegen/node_modules/readable-stream/lib/_stream_readable.js:198:18)
    at RandomStream.Readable.push (/usr/local/lib/node_modules/storj-farmer/node_modules/myspeed/node_modules/noisegen/node_modules/readable-stream/lib/_stream_readable.js:157:10)
    at InternalFieldObject.ondone (/usr/local/lib/node_modules/storj-farmer/node_modules/myspeed/node_modules/noisegen/lib/random-stream.js:63:12)
```

**Comment by gordonwritescode** [comment]
Identified. This is a bug in the speed testing module where it tries to send upload to speed test server, but the socket is closed. 

Will fix.

**Comment by gordonwritescode** [comment]
Actually these 2 errors are different. 

@CurreE - yours is related to the speed testing module, [myspeed](https://github.com/gordonwritescode/myspeed) - let's open an issue there and for now I'll just wrap the usage in storj-farmer to prevent a crash if it happens.

@lucvanbraekel - yours is actually an issue in the core library, and it's happening somewhere in here: https://github.com/Storj/core/blob/master/lib/datachannel/server.js#L112-L129 - let's open an issue in core if you run into this again after the latest updates

**Comment by CurreE** [comment]
thanks for the update, looking forward to having this fixed in the next version!
