### ISSUE TITLE
storjfarm crashes: assert.js:90

### ISSUE THREAD

**Issue by lunokhod** [Storj/farmer#30]
I was running storjfarm  for about 12 hours when it crashed with the following message
~~~~
{"type":"info","message":"sending OPEN_TUNNEL message to {\"protocol\":\"0.6.1\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1461745327470}","timestamp":"2016-04-27T08:22:07.470Z"}
{"type":"info","message":"starting local database replication","timestamp":"2016-04-27T08:22:08.640Z"}
{"type":"info","message":"starting local database replication","timestamp":"2016-04-27T08:22:08.640Z"}
{"type":"info","message":"database replication complete","timestamp":"2016-04-27T08:22:08.641Z"}
{"type":"info","message":"database replication complete","timestamp":"2016-04-27T08:22:08.641Z"}

assert.js:90
  throw new assert.AssertionError({
  ^
AssertionError: Key must be 160 bit hex string
    at FSStorageAdapter.StorageAdapter.get (/usr/local/lib/node_modules/storj-farmer/node_modules/storj/lib/storage/adapter.js:25:3)
    at /usr/local/lib/node_modules/storj-farmer/node_modules/storj/lib/storage/adapter.js:94:16
    at FSReqWrap.oncomplete (fs.js:82:15)
~~~~
After resinstalling/upgrading the software and restarting storjfarm, I get the following full output
~~~~
{"level":"warn","message":"you are not bound to a public address, trying traversal strategies...","timestamp":"2016-04-27T20:49:38.883Z"}
{"level":"info","message":"you are configured to tunnel up to 3 connections","timestamp":"2016-04-27T20:49:38.886Z"}
{"level":"info","message":"node created with nodeID b67e00024e1153a99b5ef76b74fb52ce4118275f","timestamp":"2016-04-27T20:49:38.897Z"}
{"level":"info","message":"subscribing to topic \"0e01\"","timestamp":"2016-04-27T20:49:38.899Z"}
{"level":"info","message":"subscribing to topic \"0e00\"","timestamp":"2016-04-27T20:49:38.904Z"}
{"level":"info","message":"requesting probe from nearest neighbor","timestamp":"2016-04-27T20:49:38.906Z"}
{"level":"info","message":"sending PROBE message to {\"protocol\":\"0.6.3\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1461790178907}","timestamp":"2016-04-27T20:49:38.907Z"}

assert.js:90
  throw new assert.AssertionError({
  ^
AssertionError: Key must be 160 bit hex string
    at FSStorageAdapter.StorageAdapter.get (/usr/local/lib/node_modules/storj-farmer/node_modules/storj/lib/storage/adapter.js:25:3)
    at /usr/local/lib/node_modules/storj-farmer/node_modules/storj/lib/storage/adapter.js:94:16
    at FSReqWrap.oncomplete (fs.js:82:15)
~~~~
The shards directory contains
~~~~
ls -R shards/
37e247f1d3e4fefc0e3b598650cabf14f7bfd561/

shards//37e247f1d3e4fefc0e3b598650cabf14f7bfd561:
challenges/	contracts/	meta/		shard.data	trees/

shards//37e247f1d3e4fefc0e3b598650cabf14f7bfd561/challenges:

shards//37e247f1d3e4fefc0e3b598650cabf14f7bfd561/contracts:
593844dc7f0076a1aeda9a6b9788af17e67c1052

shards//37e247f1d3e4fefc0e3b598650cabf14f7bfd561/meta:
593844dc7f0076a1aeda9a6b9788af17e67c1052

shards//37e247f1d3e4fefc0e3b598650cabf14f7bfd561/trees:
593844dc7f0076a1aeda9a6b9788af17e67c1052
~~~~
Version: OSX
Farmer: v2.2.3
Core:   v0.6.3

**Comment by lunokhod** [comment]
I deleted the shards directory and tried again with

Farmer: v2.2.3
Core:   v0.6.4

but got the same behavior.

**Comment by gordonwritescode** [comment]
Okay, that error is coming from here: https://github.com/Storj/core/blob/master/lib/storage/adapter.js#L94

This happens during the "shard reaping" task where the node check for expired contracts and reaps old shards. We do this by enumerating the items in the shard directory (https://github.com/Storj/core/blob/master/lib/storage/adapter.js#L83) and loading the storage item located at the path.

In your case, it seems there is an invalid directory name (should be 160 key), but I don't see it in your console output. Can you add the `-a` option to see if somehow there is a hidden file or directory in there?

**Comment by gordonwritescode** [comment]
Actually, this is strange, when I run `ls -R` on my shards directory, I get similar output, but no trailing `/` - I wonder if that's causing the issue?

What OS are you running? I'm on Debian 8.

**Comment by gordonwritescode** [comment]
Also just realized that we are both storing the same shard - interesting coincidence.

**Comment by gordonwritescode** [comment]
@lunokhod out of curiosity can you run the following from your shell (replace with your shards path) and paste the output here?

```
node -e "console.log(require('fs').readdirSync('/home/gordon/.storj-farmer-cli/shards'))"
```

I get:

```
[ '37e247f1d3e4fefc0e3b598650cabf14f7bfd561' ]
```

**Comment by lunokhod** [comment]
I'm running this on OSX. I think that the problem might be that OSX puts a hidden file called .DS_Store whenever you view the folder in the OSX GUI.

Here is the long output of the entire directory
~~~~
% ls -aR
./		../		.DS_Store	config.json	id_ecdsa	shards/

./shards:
./						.DS_Store
../						37e247f1d3e4fefc0e3b598650cabf14f7bfd561/

./shards/37e247f1d3e4fefc0e3b598650cabf14f7bfd561:
./		../		.DS_Store	challenges/	contracts/	meta/		trees/

./shards/37e247f1d3e4fefc0e3b598650cabf14f7bfd561/challenges:
./	../

./shards/37e247f1d3e4fefc0e3b598650cabf14f7bfd561/contracts:
./						../						593844dc7f0076a1aeda9a6b9788af17e67c1052

./shards/37e247f1d3e4fefc0e3b598650cabf14f7bfd561/meta:
./						../						593844dc7f0076a1aeda9a6b9788af17e67c1052

./shards/37e247f1d3e4fefc0e3b598650cabf14f7bfd561/trees:
./	../
~~~~
And here is the other output you asked for:
~~~~
node -e "console.log(require('fs').readdirSync('/Volumes/Lunokhod-backup/storj/shards'))"
[ '.DS_Store', '37e247f1d3e4fefc0e3b598650cabf14f7bfd561' ]
~~~~
I deleted the .DS_Store files, relaunched storjfarm and it appears to be working (at least it hasn't crashed in five minutes.)

**Comment by gordonwritescode** [comment]
That's it! Okay, I'll issue a fix Monday morning. Thanks for the help.
