### ISSUE TITLE
storjfarm crashes: Cannot read property 'address' of undefined

### ISSUE THREAD

**Issue by lunokhod** [Storj/farmer#37]
I am trying to run storjfarm on computer that is likely behind some kind of firewall that is beyond my control. This has not stopped me from participating in test groups A and B, and I am able to run things like i2p and a bitcoin node without any problems (though OpenBazaar is not working...). The following is the output after starting strojfarm.

Farmer: v2.2.6
Core:   v0.6.7
~~~~
{"level":"warn","message":"you are not bound to a public address, trying traversal strategies...","timestamp":"2016-04-30T12:30:40.162Z"}
{"level":"info","message":"you are configured to tunnel up to 3 connections","timestamp":"2016-04-30T12:30:40.167Z"}
{"level":"info","message":"node created with nodeID a1844cfb38527bedcdce8a7e28b44fe1d1fe7183","timestamp":"2016-04-30T12:30:40.182Z"}
{"level":"info","message":"requesting probe from nearest neighbor","timestamp":"2016-04-30T12:30:40.185Z"}
{"level":"info","message":"sending PROBE message to {\"protocol\":\"0.6.7\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1462019440188}","timestamp":"2016-04-30T12:30:40.188Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.6.6\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1462019440521}","timestamp":"2016-04-30T12:30:40.521Z"}
{"level":"info","message":"requesting tunnelers from nearest neighbor","timestamp":"2016-04-30T12:30:40.583Z"}
{"level":"info","message":"sending FIND_TUNNEL message to {\"protocol\":\"0.6.7\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1462019440584}","timestamp":"2016-04-30T12:30:40.584Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.6.6\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1462019440894}","timestamp":"2016-04-30T12:30:40.895Z"}
{"level":"info","message":"sending OPEN_TUNNEL message to {\"protocol\":\"0.6.6\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1462019440964}","timestamp":"2016-04-30T12:30:40.964Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.6.6\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1462019441261}","timestamp":"2016-04-30T12:30:41.262Z"}
/usr/local/lib/node_modules/storj-farmer/node_modules/storj/lib/network/index.js:494
    var local = 'http://127.0.0.1:' + self._transport._server.address().port;
                                                             ^

TypeError: Cannot read property 'address' of undefined
    at /usr/local/lib/node_modules/storj-farmer/node_modules/storj/lib/network/index.js:494:62
    at /usr/local/lib/node_modules/storj-farmer/node_modules/async/lib/async.js:789:30
    at /usr/local/lib/node_modules/storj-farmer/node_modules/async/lib/async.js:167:37
    at Object.callback (/usr/local/lib/node_modules/storj-farmer/node_modules/storj/lib/network/index.js:483:7)
    at Transport.RPC._execPendingCallback (/usr/local/lib/node_modules/storj-farmer/node_modules/kad/lib/rpc.js:280:17)
    at /usr/local/lib/node_modules/storj-farmer/node_modules/kad/lib/rpc.js:184:12
    at /usr/local/lib/node_modules/storj-farmer/node_modules/kad/lib/rpc.js:254:5
    at /usr/local/lib/node_modules/storj-farmer/node_modules/kad/node_modules/async/lib/async.js:251:17
    at /usr/local/lib/node_modules/storj-farmer/node_modules/kad/node_modules/async/lib/async.js:154:25
    at /usr/local/lib/node_modules/storj-farmer/node_modules/kad/node_modules/async/lib/async.js:248:21
~~~~

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/core/issues/68

**Comment by gordonwritescode** [comment]
This will be resolved by https://github.com/Storj/core/pull/74
