### ISSUE TITLE
telemetry issue

### ISSUE THREAD

**Issue by silaxe** [Storj/farmer#42]
I am trying to run storjfarm (Farmer v2.2.7; Core v0.6.10) on a raspberry pi (Jessy) with the below config file:

 ```
{
  "keypath": "/home/pi/nfs/PK",
  "address": "16bBiJKzBSnawq1n2KrY12SAmBemPmEcwf",
  "storage": {
    "path": "/home/pi/nfs/Storj",
    "size": 500,
    "unit": "GB"
  },
  "network": {
    "address": "127.0.0.1",
    "port": 0,
    "seeds": [
      "storj://api.storj.io:8443/593844dc7f0076a1aeda9a6b9788af17e67c1052"
    ],
    "opcodes": [
      "0f01020202",
      "0f02020202",
      "0f03020202"
    ],
    "forward": true,
    "tunnels": 3,
    "tunnelport": 0,
    "gateways": {
      "min": 0,
      "max": 0
    }
  },
  "telemetry": {
    "service": "https://status.storj.io",
    "enabled": true
  }
}
```

Unfortunately I am getting the results below:

```
{"level":"warn","message":"you are not bound to a public address, trying traversal strategies...","timestamp":"2016-05-05T20:25:07.353Z"}
{"level":"info","message":"you are configured to tunnel up to 3 connections","timestamp":"2016-05-05T20:25:07.438Z"}
{"level":"warn","message":"could not connect to NAT device via UPnP","timestamp":"2016-05-05T20:25:09.490Z"}
{"level":"info","message":"node created with nodeID cc90d88934e6921d14e209aa156d6d9c510f22a9","timestamp":"2016-05-05T20:25:09.635Z"}
{"level":"info","message":"requesting probe from nearest neighbor","timestamp":"2016-05-05T20:25:09.698Z"}
{"level":"info","message":"sending PROBE message to {\"protocol\":\"0.6.10\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1462479909748}","timestamp":"2016-05-05T20:25:09.749Z"}
{"level":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.6.10\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1462479913752}","timestamp":"2016-05-05T20:25:13.753Z"}

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: not implemented
    at Writable._write (_stream_writable.js:325:6)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at Writable.write (_stream_writable.js:183:11)
    at WebSocket.<anonymous> (/usr/local/lib/node_modules/storj-farmer/node_modules/myspeed/lib/client.js:54:18)
    at WebSocket.emit (events.js:98:17)
    at Receiver.onbinary (/usr/local/lib/node_modules/storj-farmer/node_modules/myspeed/node_modules/ws/lib/WebSocket.js:848:10)
    at /usr/local/lib/node_modules/storj-farmer/node_modules/myspeed/node_modules/ws/lib/Receiver.js:628:18
    at /usr/local/lib/node_modules/storj-farmer/node_modules/myspeed/node_modules/ws/lib/Receiver.js:368:7
    at /usr/local/lib/node_modules/storj-farmer/node_modules/myspeed/node_modules/ws/lib/PerMessageDeflate.js:249:5
```

When disabling telemetry: 

```
{"level":"warn","message":"you are not bound to a public address, trying traversal strategies...","timestamp":"2016-05-05T20:34:07.757Z"}
{"level":"info","message":"you are configured to tunnel up to 3 connections","timestamp":"2016-05-05T20:34:07.842Z"}
{"level":"info","message":"successfully traversed NAT via UPnP","timestamp":"2016-05-05T20:34:09.686Z"}
{"level":"info","message":"node created with nodeID cc90d88934e6921d14e209aa156d6d9c510f22a9","timestamp":"2016-05-05T20:34:09.826Z"}
{"level":"info","message":"publishing message on topic \"0e01\"","timestamp":"2016-05-05T20:34:09.958Z"}
{"level":"info","message":"subscribing to topic \"0e01\"","timestamp":"2016-05-05T20:34:09.967Z"}
{"level":"info","message":"subscribing to topic \"0e00\"","timestamp":"2016-05-05T20:34:10.050Z"}
{"level":"info","message":"subscribing to topic \"0f01020202\"","timestamp":"2016-05-05T20:34:10.112Z"}
{"level":"info","message":"subscribing to topic \"0f02020202\"","timestamp":"2016-05-05T20:34:10.170Z"}
{"level":"info","message":"subscribing to topic \"0f03020202\"","timestamp":"2016-05-05T20:34:10.226Z"}
{"level":"info","message":"subscribing to topic \"0f01020202\"","timestamp":"2016-05-05T20:34:10.281Z"}
{"level":"info","message":"subscribing to topic \"0f02020202\"","timestamp":"2016-05-05T20:34:10.345Z"}
{"level":"info","message":"subscribing to topic \"0f03020202\"","timestamp":"2016-05-05T20:34:10.401Z"}
{"level":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.6.10\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1462480450627}","timestamp":"2016-05-05T20:34:10.629Z"}
{"level":"warn","message":"missing or empty reply from contact","timestamp":"2016-05-05T20:34:22.980Z"}
{"level":"warn","message":"rpc call 9176e74bbef50665e88df86b1e4080efbe76e311 timed out","timestamp":"2016-05-05T20:34:27.849Z"}
{"level":"warn","message":"query failed, removing contact for shortlist, reason RPC with ID `9176e74bbef50665e88df86b1e4080efbe76e311` timed out","timestamp":"2016-05-05T20:34:27.858Z"}

(...)
```

In the case above, the program does not stop unexpectedly. However, nothing appears in the shard folder after a while.

Any ideas how to solve this are very much welcome!

Thanks and apologies if anything is unclear.

**Comment by gordonwritescode** [comment]
Thanks for reporting. Can you please open this issue at https://github.com/gordonwritescode/myspeed/issues?
