### ISSUE TITLE
Farmer crashed TypeError: Cannot read property 'storage' of undefined

### ISSUE THREAD

**Issue by littleskunk** [Storj/farmer#5]
```
{"type":"info","message":"sent telemetry report \"Success\"","timestamp":"2016-04-10T22:43:42.747Z"}{"type":"info","message":"sending PING message to {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460328497386}","timestamp":"2016-04-10T22:48:17.387Z"}
{"type":"info","message":"sending PING message to {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460328497386}","timestamp":"2016-04-10T22:48:17.387Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460328497928}","timestamp":"2016-04-10T22:48:17.928Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460328497928}","timestamp":"2016-04-10T22:48:17.928Z"}
/usr/local/lib/node_modules/storj-farmer/bin/farmer.js:207
    getDirectorySize(config.storage.path, function(err, size) {
                           ^

TypeError: Cannot read property 'storage' of undefined
    at send (/usr/local/lib/node_modules/storj-farmer/bin/farmer.js:207:28)
    at report [as _onTimeout] (/usr/local/lib/node_modules/storj-farmer/bin/farmer.js:284:5)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by littleskunk** [comment]
I did the same test again. The frist telemetry report is working but the second one crash. Looks like the first report set config to undefined at the end.
