### ISSUE TITLE
wizzard crashed error: EISDIR illegal operation on a directory

### ISSUE THREAD

**Issue by littleskunk** [Storj/farmer#9]
```
store configuration and data >>  (/root/.storj-farmer-cli) /mnt/data0/storj/
error:   Directory already exists, refusing to overwrite
 STORJ-FARMER-CLI >> Enter the path to store configuration and data >>  (/root/.storj-farmer-cli) /mnt/data1/storj/
 STORJ-FARMER-CLI >> Enter the amount of storage space you can share >>  (5MB) 5TB
 STORJ-FARMER-CLI >> Enter a payment address to receive rewards (telemetry must be enabled) >>  13fKDBMJ28deNETvpwJWwWjYraicePyDXC
 STORJ-FARMER-CLI >> Will you share telemetry data with Storj to help improve the network? >>  (false) true
 STORJ-FARMER-CLI >> Enter the path to store your encrypted private key >>  (/root/.storj-farmer-cli/id_ecdsa)
error:   Cannot write key to path that does not exist
 STORJ-FARMER-CLI >> Enter the path to store your encrypted private key >>  (/root/.storj-farmer-cli/id_ecdsa) /mnt/data1/
 STORJ-FARMER-CLI >> Enter a password to protect your private key >>  ******
 
readline.js:925
            throw err;
            ^
 
Error: EISDIR: illegal operation on a directory, open '/mnt/data1/'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at /usr/lib/node_modules/storj-farmer/bin/farmer.js:408:8
    at /usr/lib/node_modules/storj-farmer/node_modules/prompt/lib/prompt.js:336:32
    at /usr/lib/node_modules/storj-farmer/node_modules/prompt/node_modules/utile/node_modules/async/lib/async.js:154:25
    at assembler (/usr/lib/node_modules/storj-farmer/node_modules/prompt/lib/prompt.js:333:9)
    at /usr/lib/node_modules/storj-farmer/node_modules/prompt/lib/prompt.js:342:32
    at /usr/lib/node_modules/storj-farmer/node_modules/prompt/lib/prompt.js:625:5
    at Interface.onLine (/usr/lib/node_modules/storj-farmer/node_modules/prompt/node_modules/read/lib/read.js:111:5)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:169:7)
    at Interface._onLine (readline.js:211:10)
    at Interface._line (readline.js:550:8)
    at Interface._ttyWrite (readline.js:827:14)
    at ReadStream.onkeypress (readline.js:106:10)
 
 
 storjfarm -d /mnt/data1/storj/
fs.js:603
  var r = binding.read(fd, buffer, offset, length, position);
                  ^
 
Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:603:19)
    at Object.fs.readFileSync (fs.js:438:24)
    at start (/usr/lib/node_modules/storj-farmer/bin/farmer.js:302:20)
    at Object.<anonymous> (/usr/lib/node_modules/storj-farmer/bin/farmer.js:416:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by littleskunk** [comment]
dupplicate: https://github.com/Storj/farmer/issues/8
